vert:
  port: 8000
  work-pool-size: 400
  instance: 16

#mongo:
#  host: 127.0.0.1
#  port: 27017
#  username: advanpro_dev_dba
#  password: iKt3jm2HDy9iZyRB
#  authSource: advanpro_cms_test_db
#  authSource: yapi



#spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#  jpa:
#    database: h2
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
