vert:
  port: 8000
  work-pool-size: 200
  instance: 1
  ha: true
#  eventBusOptions:
#    clusterPublicPort: ${publicPort}
#    clusterPublicHost: ${publicHost}
#    clusterPublicHost: 192.168.10.164
#    clusterPublicPort: 19000
#    port: 9000
#    host: 0.0.0.0
#    clustered: true

mongo:
  host: 127.0.0.1
  port: 27017
  username: dev
  password: 123456
  authSource: develop



#spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#  jpa:
#    database: h2
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  h2:
#    console:
#      path: /h2-console
#      enabled: true
